version: '3.8'

services:
  pedido-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pedido-app
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin123@mongodb-pedido:27017/db_pedido?authSource=admin
      - SPRING_PROFILES_ACTIVE=prod
      - CLIENTE_SERVICE_URL=http://cliente-app:8080
    depends_on:
      mongodb-pedido:
        condition: service_healthy
    networks:
      - pedido-network
      - microservices-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb-pedido:
    image: mongo:7.0
    container_name: mongodb-pedido
    ports:
      - "27018:27017"  # Porta externa 27018 → Interna 27017
    volumes:
      - mongodb_pedido_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=db_pedido
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - pedido-network
    restart: unless-stopped

networks:
  pedido-network:
    driver: bridge
    name: pedido-network  # Nome explícito para conexão entre serviços
  microservices-net:
    external: true


volumes:
  mongodb_pedido_data: